export const videogames = [
  {
    "id": 1,
    "title": "The Legend of Zelda: The Wind Waker",
    "year": 2002,
    "developer": "Nintendo",
    "console": "GameCube, Wii U",
    "image": "https://assets1.ignimgs.com/2019/06/04/legend-of-zelda-the-wind-waker---button-1559683061504.jpg",
    "rating": 5,
  },
  {
    "id": 2,
    "title": "Kid Icarus: Uprising",
    "year": 2012,
    "developer": "Nintendo",
    "console": "Nintendo 3DS",
    "image": "https://m.media-amazon.com/images/M/MV5BYjlhMWJhNmMtZTQ4MS00N2I1LTkyMmEtZTRjYzQ3MTZmOGZlXkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_FMjpg_UX1000_.jpg",
    "rating": 4.5,
  },
  {
    "id": 3,
    "title": "Forza Horizon 4",
    "year": 2018,
    "developer": "Turn 10 Studios, Playground Gamess",
    "console": "Xbox One",
    "image": "https://upload.wikimedia.org/wikipedia/en/8/87/Forza_Horizon_4_cover.jpg",
    "rating": 4,
  },
  {
    "id": 4,
    "title": "Animal Crossing: New Horizons",
    "year": 2020,
    "developer": "Nintendo",
    "console": "Nintendo Switch",
    "image": "https://nharrowhead.com/wp-content/uploads/2020/04/Animal-Crossing_-New-Horizons.png",
    "rating": 4,
  },
  {
    "id": 5,
    "title": "My Hero One's Justice",
    "year": 2002,
    "developer": "Byking, BANDAI NAMCO",
    "console": "Nintendo Switch",
    "image": "https://www.mobygames.com/images/covers/l/511453-my-hero-one-s-justice-nintendo-switch-front-cover.jpg",
    "rating": 4.5,
  },
  {
    "id": 6,
    "title": "Disney Infinity",
    "year": 2013,
    "developer": "Disney Interactive Studios",
    "console": "Wii, Wii U",
    "image": "https://www.mobygames.com/images/covers/l/280446-disney-infinity-wii-u-other.jpg",
    "rating": 4.5,
  },
  {
    "id": 7,
    "title": "The Legend of Zelda: Skyward Sword",
    "year": 2011,
    "developer": "Nintendo",
    "console": "Wii, Wii U, Nintendo Switch",
    "image": "https://assets-prd.ignimgs.com/2021/02/23/zelda-skyward-sword-hd-button-1614064616471.jpg",
    "rating": 4.5,
  },
  {
    "id": 8,
    "title": "Kingdom Hearts HD 1.5 Remix",
    "year": 2013,
    "developer": "Square Enix",
    "console": "Xbox One, Nintendo Switch",
    "image": "https://m.media-amazon.com/images/M/MV5BYzhjNWRlYTgtZGVmNi00M2RlLTkzZWMtODVjMzgzNDRlY2E2XkEyXkFqcGdeQXVyNjc3OTE4Nzk@._V1_.jpg",
    "rating": 4,
  },
  {
    "id": 9,
    "title": "Super Smash Bros. Ultimate",
    "year": 2018,
    "developer": "Nintendo, BANDAI NAMCO Studios",
    "console": "Nintendo Switch",
    "image": "https://www.mobygames.com/images/covers/l/548925-super-smash-bros-ultimate-nintendo-switch-front-cover.jpg",
    "rating": 5,
  },
  {
    "id": 10,
    "title": "The Legend of Zelda: Breath of the Wild",
    "year": 2017,
    "developer": "Nintendo",
    "console": "Wii U, Nintendo Switch",
    "image": "https://www.gamespot.com/a/uploads/scale_medium/1197/11970954/3181241-ig-lozbreathofthewildrelease-20170112.jpg",
    "rating": 4.5,
  }
]